### ISSUE TITLE
目安箱: 10/6 プログラム・コンパイラ・実行の内容の質問箱

### ISSUE THREAD

**Issue by wakita** [titech-is-cs115/lecture#1]
初回の講義について．
- ソフトウェアの設計図にあたるプログラムについて：機械語のプログラム，高級言語で記述したプログラム
- プログラムの実行方式：機械語の直接実行方式，コンパイル＆直接実行方式，インタプリタ実行方式，仮想機械上での実行方式
  - 機械語とアセンブリ言語
- Scala のプログラムとその実行方式
  - インタプリタを用いた実行
  - コンパイラと仮想機械を用いた実行
  - 開発環境 (sbt) を用いた実行
    - sbt の起動
    - コンパイル
    - 実行
    - インタプリタの実行
    - 継続的コンパイル環境
    - 継続的実行環境
- 講義資料の入手方法

**Comment by wakita** [comment]
Issue tracker の使い方を練習しましょう．みんなでシリトリをしましょう．ただのシリトリではつまらないので**情報科学**縛りでいきましょう．情報科学に関係する言葉だけでシリトリをします．では，最初は私から

**計算機科学**

次の方は「ク」ですよ．

**Comment by Yukits** [comment]
https://titech-is-cs115.github.io/lecture/assignments/lx00a
>sbtを用いた普通の作業方法を通して，compileコマンド，runコマンド，exitコマンドの使い方について学びます．作業用ディレクトリを**cs1**に変更してから，講義資料の「sbtの利用」の作業を実施してみて下さい

cs1ディレクトリでcloneしてsbtを起動してrunをしても動きませんでした。(No main class detected)
01a(scalaファイルがある場所)に移動するとrunできました。

**Comment by wakita** [comment]
特に質問はなさそうなので閉じます．
