### ISSUE TITLE
Issue trackerの練習：情報科学シリトリ

### ISSUE THREAD

**Issue by wakita** [titech-is-cs115/lecture#2]
Issue tracker の使い方を練習しましょう．みんなでシリトリをしましょう．ただのシリトリではつまらないので**「情報科学」縛り**でいきましょう．情報科学に関係する言葉だけでシリトリをします．では，最初は私から**計算機科学**

次の方は「ク」ですよ．

**Comment by ryuhei-mori** [comment]
**クロージャ**

**Comment by wakita** [comment]
ヤコビ行列

**Comment by 3tty0n** [comment]
ツリー構造

**Comment by nikeeshi** [comment]
ウエルチ検定

**Comment by RyoAshida** [comment]
遺伝アルゴリズム

**Comment by Yukits** [comment]
ムーアの法則

**Comment by ozu5** [comment]
クイックソート

**Comment by tazoe5** [comment]
トポロジー

**Comment by ghost** [comment]
情報エントロピー

**Comment by ghost** [comment]
ピタゴラスの定理

**Comment by tomoya6092** [comment]
リーマン可積分関数

**Comment by horibee** [comment]
ウォーターマーク

**Comment by urihari** [comment]
空集合

**Comment by kyojikato** [comment]
windows user 少ない

**Comment by tkke** [comment]
位相解析

**Comment by kazuibasou** [comment]
幾何

**Comment by takakuuu** [comment]
仮想機械

**Comment by moriken4** [comment]
インターネット

**Comment by kyojikato** [comment]
トポロジー

**Comment by urihari** [comment]
トポロジー既出

**Comment by hyoukaija** [comment]
通信

**Comment by Miyazak5** [comment]
トップダウン方式

**Comment by ShotaTakahashi** [comment]
木

**Comment by RinoIsahai** [comment]
機械学習

**Comment by tamai14** [comment]
共通鍵

**Comment by TasukuKominato** [comment]
Git

**Comment by wakita** [comment]
tree

**Comment by wakita** [comment]
e-コマース --- （なんとか，日本語に戻した）

**Comment by tamai14** [comment]
scala

**Comment by KSato0428** [comment]
algorithm

**Comment by TakeshiOhzu** [comment]
memory

**Comment by tamura0629** [comment]
y座標

**Comment by RinoIsahai** [comment]
Web2.0

**Comment by maiejunya** [comment]
ブラウザ

**Comment by RinoIsahai** [comment]
在宅勤務

**Comment by masudatakuto** [comment]
無限小

**Comment by RinoIsahai** [comment]
打ち切り誤差

**Comment by nobukuni** [comment]
最小二乗法

**Comment by Yukits** [comment]
ウェアラブルコンピューティング

**Comment by RinoIsahai** [comment]
グーグル

**Comment by Yukits** [comment]
ruby

**Comment by RinoIsahai** [comment]
インタプリタ

**Comment by Yukits** [comment]
タグ

**Comment by RinoIsahai** [comment]
偶関数

**Comment by Yukits** [comment]
ウイルス

**Comment by 3tty0n** [comment]
スーパーハッカー

**Comment by RinoIsahai** [comment]
暗号鍵

**Comment by 3tty0n** [comment]
ギットハブ

**Comment by RinoIsahai** [comment]
ブックマーク

**Comment by ikegami5** [comment]
クラウド

**Comment by Yukits** [comment]
ドッカー

**Comment by RinoIsahai** [comment]
感圧タッチ

**Comment by 3tty0n** [comment]
チューリングマシン

**Comment by ghost** [comment]
お疲れ様でーす

**Comment by RinoIsahai** [comment]
\(^o^)/

**Comment by RinoIsahai** [comment]
_

**Comment by wakita** [comment]
チューリング機械

**Comment by 3tty0n** [comment]
インタープリタ

**Comment by wakita** [comment]
大数の法則

**Comment by rkrk9** [comment]
クエリ

**Comment by RinoIsahai** [comment]
量子コンピュータ

**Comment by masudatakuto** [comment]
体

**Comment by nanashima** [comment]
インスタンス

**Comment by yudaitnb** [comment]
Steganography

**Comment by wakita** [comment]
[Y-コンビネータ](https://www.google.co.jp/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0CB8QFjAAahUKEwjJxpLX3LHIAhVBu5QKHfG3DbU&url=https%3A%2F%2Fja.wikipedia.org%2Fwiki%2F%25E4%25B8%258D%25E5%258B%2595%25E7%2582%25B9%25E3%2582%25B3%25E3%2583%25B3%25E3%2583%2593%25E3%2583%258D%25E3%2583%25BC%25E3%2582%25BF&usg=AFQjCNHa5gwaLvZbf6ZJo2QXvfuiTAzkYw&sig2=HdwhnEjTdP7jdcF92hFs7Q)

---

計算論の体系のなかでλ計算と等価なコンビネータ理論があります．そのなかで一般再帰関数と深く関わる概念がY-コンビネータで，[不動点コンビネータ](https://www.google.co.jp/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0CB8QFjAAahUKEwjJxpLX3LHIAhVBu5QKHfG3DbU&url=https%3A%2F%2Fja.wikipedia.org%2Fwiki%2F%25E4%25B8%258D%25E5%258B%2595%25E7%2582%25B9%25E3%2582%25B3%25E3%2583%25B3%25E3%2583%2593%25E3%2583%258D%25E3%2583%25BC%25E3%2582%25BF&usg=AFQjCNHa5gwaLvZbf6ZJo2QXvfuiTAzkYw&sig2=HdwhnEjTdP7jdcF92hFs7Q)とも呼ばれます．

**Comment by yudaitnb** [comment]
TaPL

---

註 by k. wakita

Benjamin Pierce による型理論の標準的な教科書 [Types and Programming Languages](http://www.amazon.co.jp/dp/0262162091) のこと。（普通は TAPL と略されると思うけど）。[日本語訳](http://www.amazon.co.jp/exec/obidos/ASIN/4274069117/amazon0ab-22/ref=nosim/)が出ています。

**Comment by wakita** [comment]
L値

---

えるち

手続き型言語において、代入対象となり得る構文要素のこと。変数名、配列の要素、オブジェクトのフィールド、ポインタのdereferenceなどが挙げられる。

**Comment by nishiwa5** [comment]
チューリング完全

**Comment by yudaitnb** [comment]
チューリング機械

**Comment by Miyazak5** [comment]
インライン

**Comment by wakita** [comment]
[地球シミュレータ](https://www.jamstec.go.jp/es/jp/)

地球シミュレータはスーパーコンピュータです。2002年6月の性能計測で、断トツ世界一位をたたきだし、米国を震撼させ、その後のスーパーコンピュータ競争に火をつけたと言われています。ただ、価格性能比が悪い（つまり、コスト高）点が後に批判の的にもなりました。

---

書き間違えたコメント欄の右の方の鉛筆ツールを使えば、書き直せますよ。チューリング機械は既出なので「ち」からやりなおしました。

@Miyazak5 **インライン展開**と言えばよかったのに。。。（洒落なの？）

**Comment by wakita** [comment]
タプル

---

Tuple: 組のこと。二つの組は pair、三つ組は triple、組一般は tupleといいます。

**Comment by Miyazak5** [comment]
Ruby on Rails

**Comment by wakita** [comment]
[Sコンビネータ](https://ja.wikipedia.org/wiki/SKIコンビネータ計算)

---

コンビネータ理論においてKコンビネータとともに現れる原始的なコンビネータ．Substitution combinator とも呼ばれるらしい．
