### ISSUE TITLE
Sublime Text で .gitconfig が開けません。助けて！

### ISSUE THREAD

**Issue by ryuhei-mori** [titech-is-cs115/lecture#3]

**Comment by ryuhei-mori** [comment]
以下の人が解決法を紹介していました。
http://apple.stackexchange.com/questions/64324/how-do-i-get-sublime-texts-open-file-gui-to-show-hidden-files

**Open**をしてから、`Command+Shift+.`するとよいようです。

**Comment by wakita** [comment]
解決したので閉じます．
