### ISSUE TITLE
scalac とか sbt を起動できません。

### ISSUE THREAD

**Issue by ryuhei-mori** [titech-is-cs115/lecture#4]

**Comment by ryuhei-mori** [comment]
環境設定が足りてないようです。

ホームの直下の `.bash_profile`というテキストファイルに以下の記述を追加してください。
`.bash_profile`が存在しないときは新たに作成してください。

```
PATH=/home/wakita/brew/bin:$PATH
```

ファイルを修正したら、ターミナルをいったん終了してから、もう一度起動してください。

**Comment by wakita** [comment]
ひとまず解決したので閉じます．
