### ISSUE TITLE
sbt の起動が死ぬほど遅いです。なんとかして下さい。

### ISSUE THREAD

**Issue by ikegami5** [titech-is-cs115/lecture#5]

**Comment by ikegami5** [comment]
（自作自演ですが。。。）

ターミナルで以下のコマンドを実行するといいです。ひとまず、sbt を殺してください。

```
cd
mv .sbt .sbt-bak
mv .ivy2 .ivy2-bak
cp -r /home/wakita/{.ivy2,.sbt} .
```

脇田先生が前の日にダウンロードした sbt のモジュールがあるのでそれをコピーしておくと、ネットにアクセスしないので起動が速くなるようです。

**Comment by wakita** [comment]
ひとまず解決したので閉じます．
