### ISSUE TITLE
sbtを実行するディレクトリについて

### ISSUE THREAD

**Issue by Yukits** [titech-is-cs115/lecture#6]
https://titech-is-cs115.github.io/lecture/assignments/lx00a

> sbtを用いた普通の作業方法を通して，compileコマンド，runコマンド，exitコマンドの使い方について学びます．作業用ディレクトリをcs1に変更してから，講義資料の「sbtの利用」の作業を実施してみて下さい
## 

cs1ディレクトリでcloneしてsbtを起動してrunをしても動きませんでした。(No main class detected)
01a(scalaファイルがある場所)に移動するとrunできました。

**Comment by wakita** [comment]
資料の書き間違えかもしれません．

`cs1/lecture` で試していただけませんか．

**Comment by Yukits** [comment]
cs1/lectureでできました。

---

実行結果

```
{"family":"あなたの姓に書き換えて下さい","name":"あなたの名に書き換えて下さい","id":"あなたの学籍番号に書き換えて下さい","login":"あなたのログインIDに書き換えて下さい","email":"あなたの東工大メールのアドレスの@から左の部分に書き換えて下さい"}
[success] Total time: 62 s, completed 2015/10/06 16:57:28
```

**Comment by wakita** [comment]
了解です．問題が収束したようなので，この Issue は閉じます．
