### ISSUE TITLE
目安箱: 10/13 単体テスト，テスト駆動開発

### ISSUE THREAD

**Issue by wakita** [titech-is-cs115/lecture#7]
- 講義資料の誤りについての指摘
- わかりにくい点の指摘
- 講義中の説明で不明な点
- 講義と関係ないこともないけど，やっぱり関係ないかもしれないこと

などなど，

建設的なご意見は成績に反映します．そうでないコメントは減点の対象とはしません．

ですので，お気軽にお寄せ下さい．

**Comment by ghost** [comment]
次回講義の講義資料を印刷してから講義に臨みたいのですが、pdfのアップはいつごろを予定していますか？

**Comment by wakita** [comment]
完成度は低いのですが、ひとまずアップロードしておきます。お昼までにアップデートします。

4c8afbd14d9790dc34d0063b7d85bdf708b1cfec

**Comment by wakita** [comment]
- :white_flower: `:white_flower:`
- :100: `:100:`
- :heavy_check_mark: `:heavy_check_mark:`
-  :clap: `:clap:`
- :smile: `:smile:`
- :confused: `:confused:`
- :worried: `:worried:`
- :sob: `:sob:`
-  :angry: `:angry:`
-  :+1: `:+1:`
- :-1: `:-1:`
